### ISSUE TITLE
Lock memory failed

### ISSUE THREAD

**Issue by empty814** [antonilo/vision_locomotion#4] opened 2023-05-14 03:38 UTC
@antonilo @ashish-kmr 
Hi,
    Thank you for sharing the code. However, I encountered a problem when deploying and would like to ask for your advice. The error message is “lock memory failed”, I have added the permissions as you said, and also tried “sudo su”, but it still doesn’t work. I traced it back to line 311 in “src/agile_locomotion/controller/src/agile_locomotion.cpp” where “InitEnvironment();” is called. 
1. However, I can only trace back to “quadruped.h” and can’t find the definition of “InitEnvironment()”. Do you have it?
2. I suspect it may be a version issue with “Unitree_legged_sdk”. May I ask which version you’re using?

**Comment by antonilo** [comment] 2023-05-17 17:43
Hi @empty814,

As discussed over email, this was a problem with the SDK. I will add it in the readme. Feel free to close the issue if the problem is solved

**Closed as completed** 2023-05-18 11:15 UTC
